version: '3'

services:
  node:
    build: 
      context: .
      dockerfile: node.Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
        PROJECT_FOLDER: ${PROJECT_FOLDER}
    depends_on: 
      - db
    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment: 
      - PROJECT_FOLDER
    # Comment the next line to use root for all processes.
    user: node

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ../wp-data:/docker-entrypoint-initdb.d

  wordpress:
    build: 
      context: .
      dockerfile: wordpress.Dockerfile
    depends_on:
      - node
      - db
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    env_file: 
      - .env
    environment:
      WORDPRESS_DB_HOST: db
    volumes:
      - wordpress:/var/www/html
      - ../${PROJECT_TYPE}:/var/www/html/wp-content/plugins/${PROJECT_NAME}

volumes:
  wordpress:
  db:
  node_modules: